//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.01 at 01:15:12 AM COT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://localhost/soap/api/WelcomePost", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.example.psn_interface.soapConfig.SoapClasses;
