version: '4.17'
services:
  psn-openldap-service:
    image: osixia/openldap:latest
    container_name: psn-openldap-service
    hostname: psn-openldap-service
    ports: 
      - "389:389"
      - "636:636"
    volumes:
      - ./data/certificates:/container/service/slapd/assets/certs
      - ./data/slapd/database:/var/lib/ldap
      - ./data/slapd/config:/etc/ldap/slapd.d
    environment: 
      - LDAP_ORGANISATION=pawsomenetwork
      - LDAP_DOMAIN=pawsomenetwork.com
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=admin_pass
      - LDAP_CONFIG_PASSWORD=config_pass
      - LDAP_BASE_DN=dc=pawsomenetwork,dc=com
      - LDAP_TLS_CRT_FILENAME=server.crt
      - LDAP_TLS_KEY_FILENAME=server.key
      - LDAP_TLS_CA_CRT_FILENAME=pawsomenetwork.com.ca.crt
      - LDAP_READONLY_USER=true
      - LDAP_READONLY_USER_USERNAME=user-ro
      - LDAP_READONLY_USER_PASSWORD=ro_pass
    networks:
      - psn_network
  
  psn-phpldapadmin-service:
    image: osixia/phpldapadmin:latest
    container_name: psn-phpldapadmin-service
    hostname: psn-phpldapadmin-service
    ports: 
      - "4003:80"
    environment: 
      - PHPLDAPADMIN_LDAP_HOSTS=psn-openldap-service
      - LDAP_HOSTS=psn-openldap-service
      - PHPLDAPADMIN_HTTPS=false
    depends_on:
      - psn-openldap-service
    networks:
      - psn_network

  psn-authentication-db-service:
    build: ../psn_authentication/psn_authentication_db
    container_name: psn-authentication-db-service
    hostname: psn-authentication-db-service
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=psn-authentication-db
      - MYSQL_USER=psn_admin
      - MYSQL_PASSWORD=123
    networks:
      - psn_network

  psn-phpmyadmin-service:
    image: phpmyadmin/phpmyadmin
    container_name: psn-phpmyadmin-service
    ports:
      - "4002:80"
    environment:
      PMA_HOST: psn-authentication-db-service
    depends_on:
      - psn-authentication-db-service
    networks:
      - psn_network

  psn-authentication-ms-service:
    build: ../psn_authentication/psn_authentication_ms
    container_name: psn-authentication-ms-service
    hostname: psn-authentication-ms-service
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=psn-authentication-db-service
      - DB_PORT=3306
      - DB_USER=psn_admin
      - DB_PASSWORD=123
      - DB_NAME=psn-authentication-db
      - PSN_WA=localhost

      - LDAP_HOST=psn-openldap-service
      - LDAP_PORT=389
      - LDAP_BASE=dc=pawsomenetwork,dc=com
      - LDAP_USER=cn=admin,dc=pawsomenetwork,dc=com
      - LDAP_PASSWORD=admin_pass
    depends_on:
      - psn-authentication-db-service
      - psn-openldap-service
    networks:
      - psn_network

  psn-ur-db-service:
    image: neo4j
    container_name: psn-ur-db-service
    ports:
      - 7474:7474
      - 7687:7687
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=neo4j/psn12345
      - NEO4J_dbms_connector_bolt_listen__address=0.0.0.0:7687
    volumes:
      - ./db/data:/data
      - ./db/conf:/conf
      - ./db/logs:/logs
      - ./db/plugins:/plugins
    networks:
      - psn_network

  psn-ur-ms-service:
    image: psn-ur-ms-service
    build: ../psn_user_relationships_ms
    container_name: psn-ur-ms-service
    ports:
      - "4200:4200"
    environment:
      - NEO4J_URI=bolt://psn-ur-db-service:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=psn12345
    volumes:
      - "./psn_user_relationships_ms:/psn-ur-ms"
    networks:
      - psn_network

#  psn-post-ms-service:
#    image: psn-post-ms-service
#    build: ../psn_post_ms
#    container_name: psn-post-ms-service
#    ports:
#      - "4100:4100"
#    environment:
#      - MONGO_URI=mongodb+srv://jrojasce:jkvUIs1rFxeB4NHR@psn-post-db.izodfgc.mongodb.net/test
#      - PORT=4100
#    networks:
#      - psn_network
#
#  psn-chat-ms-service:
#    image: psn-chat-ms-service
#    build: ../psn_chat_ms
#    container_name: psn-chat-ms-service
#    env_file:
#      - ../psn_chat_ms/.env
#    ports:
#      - "4300:4300"
#    networks:
#      - psn_network
#
#  psn-rabbitmq-service:
#    image: rabbitmq:3-management
#    container_name: psn-rabbitmq-service
#    hostname: psn-rabbitmq-service
#    volumes:
#      - /var/lib/rabbitmq
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    env_file:
#      - ../psn_notification_ms/.env
#    networks:
#      - psn_network
#
#  psn-notification-ms-service:
#    image: psn-notification-ms-service
#    build: ../psn_notification_ms
#    container_name: psn-notification-ms-service
#    env_file:
#      - ../psn_notification_ms/.env
#    ports:
#      - "4400:4400"
#    depends_on: 
#      - psn-rabbitmq-service
#    networks:
#      - psn_network
#    
#  psn-notification-ws-ms-service:
#    image: psn-notification-ws-ms-service
#    build: ../psn_notification_ws_ms
#    container_name: psn-notification-ws-ms-service
#    env_file:
#      - ../psn_notification_ws_ms/.env
#    ports:
#      - "4401:4401"
#    depends_on: 
#      - psn-rabbitmq-service
#    networks:
#      - psn_network

  psn-ag-service:
    image: psn-ag-service
    build: .
    container_name: psn-ag-service
    expose:
      - "4500"
    ports:
      - "4500:4500"
    environment:
      - SERVICE_ACCOUNT_FILE=/psn_ag/psn.json
      - BUCKET_NAME=psn_bucket1
    networks:
      - psn_network

networks:
  psn_network:
    driver: bridge