apiVersion: v1
kind: PersistentVolume
metadata:
  name: psn-openldap-persistent-volume
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /var/lib/data

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: psn-mysql-persistent-volume
spec:
  storageClassName: standard
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/lib/mysql

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: psn-neo4j-persistent-volume
spec:
  storageClassName: standard
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/lib/neo4j

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: psn-rabbitmq-persistent-volume
spec:
  storageClassName: standard
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/lib/rabbitmq

---