apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psn-rabbitmq-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  volumeName: psn-rabbitmq-persistent-volume

---