apiVersion: v1
kind: PersistentVolume
metadata:
  name: psn-rabbitmq-persistent-volume
spec:
  storageClassName: standard
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/lib/rabbitmq

---